// <auto-generated />
namespace IAAI_ARM64.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addabout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addabout));
        
        string IMigrationMetadata.Id
        {
            get { return "202403130741123_add about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
