// <auto-generated />
namespace IAAI_ARM64.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202404100708458_fixaccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
